language: cpp
compiler:
  - g++
  - clang++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8 cmake;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - g++ --version;
  - sudo apt-get update -qq;

install:
  - make install

script: 
  - cmake .
  - make 
  - make test
  - cat Testing/Temporary/*.log
